export enum StatusPedido {
    PAGAMENTO_PENDENTE = 'PAGAMENTO_PENDENTE',
    PAGAMENTO_APROVADO = 'PAGAMENTO_APROVADO',
    PROCESSANDO = 'PROCESSANDO',
    ENVIADO = 'ENVIADO',
    ENTREGUE = 'ENTREGUE',
    CANCELADO = 'CANCELADO'
}